#!/bin/sh
set -eu

cd /usr/share/iserv/server-unifios/docker/unifi-os-server
. /var/lib/iserv/server-unifios/docker-compose.env
/usr/bin/docker compose pull --quiet
/bin/systemctl restart iserv-server-unifios.service
